Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/08','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','상담 진행 예정', EMPTY_BLOB(),'모던하면서도 아름답게');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/09','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','상담 완료', EMPTY_BLOB(), EMPTY_CLOB());
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/10','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','계약 진행 중', EMPTY_BLOB(),'빠른 시공 가능 시 계약 희망');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/11','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','계약 완료', EMPTY_BLOB(),'빠른 시공 예정');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/12','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','전기 시공 시작', EMPTY_BLOB(), EMPTY_CLOB());
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/13','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','전기 시공 완료', EMPTY_BLOB(),'배선 컬러 별로 구분 완료');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/14','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','설비 시공 시작', EMPTY_BLOB(), EMPTY_CLOB());
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/15','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','설비 시공 완료', EMPTY_BLOB(),'완벽한 배치 완료');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/16','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','도배 시공 시작', EMPTY_BLOB(), EMPTY_CLOB());
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/17','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','도배 시공 완료', EMPTY_BLOB(),'오돌톨한 벽 사포질 후 벽지 완료');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/18','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','가구 시공 시작', EMPTY_BLOB(), EMPTY_CLOB());
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/19','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','가구 시공 완료', EMPTY_BLOB(),'완벽한 배치 멋지다');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/20','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','추가 시공 시작', EMPTY_BLOB(),'누수로 인한 일부 벽지 손상 확인 후 사후 처리 진행');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/21','RR/MM/DD'),'547938','서울시 송파구 송파대로 28길 43','최종 시공 완료', EMPTY_BLOB(), EMPTY_CLOB());
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/20','RR/MM/DD'),'363467','서울시 은평구 통일로 876 4층, 5층, 6층, 7층','상담 진행 예정', EMPTY_BLOB(),'모던하면서도 아름답게');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/22','RR/MM/DD'),'363467','서울시 은평구 통일로 876 4층, 5층, 6층, 7층','상담 완료', EMPTY_BLOB(), EMPTY_CLOB());
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/23','RR/MM/DD'),'363467','서울시 은평구 통일로 876 4층, 5층, 6층, 7층','계약 진행 중', EMPTY_BLOB(),'빠른 시공 가능 시 계약 희망');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/25','RR/MM/DD'),'363467','서울시 은평구 통일로 876 4층, 5층, 6층, 7층','계약 완료', EMPTY_BLOB(), EMPTY_CLOB());
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/26','RR/MM/DD'),'363467','서울시 은평구 통일로 876 4층, 5층, 6층, 7층','전기 시공 시작', EMPTY_BLOB(),'배선 컬러 별로 구분');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/29','RR/MM/DD'),'363467','서울시 은평구 통일로 876 4층, 5층, 6층, 7층','전기 시공 완료', EMPTY_BLOB(),'배선 컬러 별로 구분 완료');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/30','RR/MM/DD'),'363467','서울시 은평구 통일로 876 4층, 5층, 6층, 7층','도배 시공 시작', EMPTY_BLOB(), EMPTY_CLOB());
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/17','RR/MM/DD'),'794889','서울시 관악구 남부순환로 1912 운차빌딩','상담 진행 예정', EMPTY_BLOB(),'모던하면서도 아름답게');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/18','RR/MM/DD'),'794889','서울시 관악구 남부순환로 1912 운차빌딩','상담 완료', EMPTY_BLOB(), EMPTY_CLOB());
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/22','RR/MM/DD'),'794889','서울시 관악구 남부순환로 1912 운차빌딩','계약 진행 중', EMPTY_BLOB(),'빠른 시공 가능 시 계약 희망');
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/24','RR/MM/DD'),'794889','서울시 관악구 남부순환로 1912 운차빌딩','계약 완료', EMPTY_BLOB(), EMPTY_CLOB());
Insert into JAVA.PROGRESS (PDATE,PDLN,PADDRESS,PCATEGORY,PIMAGE,PCONTENT) values (to_date('22/04/28','RR/MM/DD'),'794889','서울시 관악구 남부순환로 1912 운차빌딩','전기 시공 시작', EMPTY_BLOB(),'배선 컬러 별로 구분');
